# -*- coding: utf-8 -*-
"""atividade_2026_03_23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13IQ-XmeZE1BJbGB6CqX0DmkFmFFPqgS-
"""

import numpy as np

# 1. Definir o Ponto P (-2, 4, 1, 1)
# Em computação gráfica, usamos vetores coluna para multiplicação de matrizes
P = np.array( [ [-2],
                [ 4],
                [ 1],
                [ 1] ] )
# 2. Definir os fatores de translação
tx, ty, tz = 5, 2, 3

# 3. Montar a Matriz de Translação 4x4 (Mt)
# Iniciamos com uma matriz identidade e preenchemos a quarta coluna
Mt = np.array( [ [1, 0, 0, tx],
                 [0, 1, 0, ty],
                 [0, 0, 1, tz],
                 [0, 0, 0, 1 ] ] )

# 4. Realizar o cálculo: P' = Mt * P
print("\nCálculo: Mt multiplicado por P...")
P_linha = np.dot(Mt, P)

# pegar linha e coluna
linhas, colunas = P_linha.shape
print("Linha x Coluna (P_linha): ",linhas, "x",colunas)

linhas_P, colunas_P = P.shape
print("Linha x Coluna (P): ",linhas_P,"x",colunas_P)

linhas_Mt, colunas_Mt = Mt.shape
print("Linha x Coluna (Mt): ",linhas_Mt,"x",colunas_Mt)

# --- Exibição dos resultados no terminal ---
print("\nMatriz de Translação (Mt):")
print(Mt)

print("\nPonto Original (P):")
print(P)

print("\nNovo Ponto Transladado (P'):")
print(P_linha)

print("\nIMPRIMINDO ELEMENTO POR ELEMENTO DA MATRIZ RESULTADO:")

for i in range(linhas):
  for j in range(colunas):
    elemento = P_linha[i][j]
    print(f"Linha {i}, Coluna {j} -> Valor: {elemento}")